version: '3'
services:
  app:
    build: ./app
    container_name: app
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/work
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: db_user
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
volumes:
  mysql_data: