version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    container_name: app
    tty: true
    environment:
      DB_DRIVER: mysql
      DB_USER: db_user
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 3306
      DB_PROTO: tcp
      DB_NAME: sample
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/work
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: db_user
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
volumes:
  mysql_data: